### ISSUE TITLE
Add comment button unusual behavior. 

### ISSUE THREAD

**Issue by 4m4n5** [amanthedorkknight/RXchange#1]
Clicking on the add comment button several times when the comment box is actually empty gives rise to the following error in the console - 
Uncaught TypeError: Cannot read property 'tagName' of null
![screenshot from 2015-07-10 13 05 12](https://cloud.githubusercontent.com/assets/7601922/8614142/532460a2-2704-11e5-9d3a-586c83e85619.png)

**Comment by sahlamba** [comment]
This was because ng-submit does not work with ng-if for some reason.
Use ng-show or ng-hide instead.
